apiVersion: apps/v1
kind: Deployment
metadata:
  name: crew-flow-server
spec:
  template:
    spec:
      containers:
        - name: crew-flow-server
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
