apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - configmap.yaml
  - ingress.yaml

commonLabels:
  environment: production

images:
  - name: rg.fr-par.scw.cloud/jb-crew-flow-registry/crew-flow-server
    newTag: prod

replicas:
  - name: crew-flow-server
    count: 1

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: crew-flow-server
