apiVersion: v1
kind: Service
metadata:
  name: crew-flow-server
  labels:
    app: crew-flow-server
    component: backend
spec:
  type: ClusterIP
  selector:
    app: crew-flow-server
    component: backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
