---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-secrets
  namespace: prod-keycloak
spec:
  encryptedData:
    admin-password: AgAr0hwxn4DJ5LQjcyPaDKBDwtpv6yfOjVupDVvLeh7aTjDtLUrp2QQO5umjc4/nMLtzzpXl0yfFOBZuzMm4BsWNtaukM5YBdcPW3JDa/my4QoMK226cg2oW5EFzw9Ub2u7UKng9DGdwsZSISFxu36mPo454W3eyVwaRb0lNKU+DUjO9A6bwBfgGssU2v/7Gmvil/NXZU4lNSZxR6X8eRbz/hHV8cDSlHycXEQyHdnubK+OH9stuBYl9KpwP47ALMVIb1QEh5dZ/d/N8RJ2EN0C0XccEk7B3aIsdKZavEC9VwV4sybU8RB0ohnZmo5/zc+6132siemKd2IQaDdiV3zwwfxFsYlQhqGlmHDZPodnar3A6j6I6WThKTgV2UtcyUt8MBUVsMKQ8MqO0UZeZrM2jCu3DcMEhkNrnRZXrGDsqm5RWkbt4L5+uCe6UBdkcQsXBYW4k6bdcfrJV2SkfXB8I+oV2Pr8JbOSZoYcqTE0HixX4p+wntCypjtFHVq4gQ5x9xsVaIN5XDqhCYRyCdVhkbyX1j8hwqvzlujXZWlDH9zblvOlq4QPFQtHsH0od+wlhCqGa5J11pJH2d5EVBhBSBU/ErvlQUfBH3v7xKdDcuBT4ay6DUbz0aXZwsmSS1PsUXt0MFR+b7rbBWi8pBDZiGNRIgBkPFsku0tj9594LaWOe3d9DJbCLiJy2/IHYfONpRt6AGSH3I2vKSZHYPHEZwolyog==
    db-password: AgBmjbv764D+AQp1/1aTafssdLU1dvpXda69G4q3kCQ46Pmk8EGsNc/TXMOtvogf6KiaJvpUONicBukmnwVz6OrUizn+gom8D/qzUFF8cfG8cl3NBV/zBcv0tX9f9giLHH9HMWE+dJiT14qpdCsxXBjtIL2Z5m1XXP9eaIlYe2msZ/M7AK5hXYm8/sfXNGrPOQNNcCCF0DeKUb+qe8yJUrQT1N9vLS/ZP1V1gibDGa8AH97ksDFc8b/nV0pw7P+Z1CZ8oFW0qIrIrBycRTv4NuNBqVZbhtpYkd3OxdbNyJXVOuFFLpUW0G/uLgvawhDw+FkPQ98OhnEptiwwLqDeFkWsmYP+lqR0rBX1CKJDR9W5iCj0Y0kXERCYg+4jn6atlZj5OzF3AxcY5+X86yUXm4wsEMP+u7FM0BqMGoYRjnRWKZn7gCxLZItzyayBK4zdqB2jlayeWU1IBHCEAjDorHkly7PngzH2bvTL4s0NFeGP8kW6UPDpDeuah7V1VNbQrCzGMUffyjK9R3XysQjmRdAb+x0b/FcAxHl1ms3lIJgc49cmVyR8gurUQV08DilDhIn7koOZ1F2AMNpMI5zZfV7YFvGLzQARqgwE/LotODDdGM6C9+M9mSk3pqLbVo6t9fwwYVtcj3v58xzveaLhSMOMhCJR0T6SnEeno9vqt6sOpt75OsLT9RLNlTAePtgbCPVem5J2qLncdTJB8xOQgQ7Ip9HzqA==
  template:
    metadata:
      name: keycloak-secrets
      namespace: prod-keycloak
